### ISSUE TITLE
prompt "unknown command 'ROLE'" when change connection

### ISSUE THREAD

**Issue by blackhuman** [ServiceStackApps/RedisReact#6]
My redis server version is 2.8.8, when i connect to it, app prompt that "unknown command 'ROLE'". Only thing that I know is that ROLE was a command that only support after Redis server version 2.8.12. How can i solve this?

**Comment by mythz** [comment]
This is a required redis server command built into the executable, so you will need to upgrade your redis-server to a version after 2.8.12.

**Comment by blackhuman** [comment]
Is there any other workaround? Because I has no direct access permission to do this? Anything I can do at client side?
