### ISSUE TITLE
Allow minimizing or hiding "Similar Keys"

### ISSUE THREAD

**Issue by kohenkatz** [ServiceStackApps/RedisReact#7]
![image](https://cloud.githubusercontent.com/assets/88755/17009683/2d794a26-4ecb-11e6-8750-aaf6e743f022.png)

As shown in this image, when keys are very long, the "Similar Keys" list hides a portion of the content of the selected key, as well as the action buttons on the top of the screen below the search bar.

There should be some option to minimize or hide the "Similar Keys" list to get around this issue.

**Comment by mythz** [comment]
Archived the Redis App in this repo in favor of [Redis Vue](https://sharpscript.net/sharp-apps/redis#redis-vue)
